server:
  port: 8085

spring:
  application:
    name: notification-service

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.example.social_service.event.NotificationEvent:com.example.notification_service.event.NotificationEvent,com.kirenz.user_service.event.NotificationEvent:com.example.notification_service.event.NotificationEvent,com.example.admin_service.notification.NotificationEvent:com.example.notification_service.event.NotificationEvent,com.kirenz.identity_service.auth.event.UserCreatedEvent:com.example.notification_service.event.UserCreatedEvent"

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET}

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      identity-service:
        base-config: default
      user-service:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 300ms
        retry-exceptions:
          - feign.RetryableException
          - java.io.IOException
    instances:
      identity-service:
        base-config: default
      user-service:
        base-config: default
