import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ChevronLeft, ChevronRight, ClipboardList } from 'lucide-react';
import { adminService } from './services/admin.service';

export default function Audit() {
  const [targetType,setTargetType]=useState(''); const [targetId,setTargetId]=useState(''); const [page,setPage]=useState(0);
  const query=useQuery({queryKey:['admin','actions',targetType,targetId,page],queryFn:()=>adminService.getActions({targetType:targetType||undefined,targetId:targetId.trim()||undefined,page,size:20})});
  return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Compliance</p><h2 className="mt-2 text-4xl font-semibold">Audit Log</h2><p className="mt-2 text-on-surface-variant">Immutable history of privileged moderation actions.</p></header><section className="grid gap-3 rounded-3xl bg-surface-container-lowest p-5 sm:grid-cols-2"><select value={targetType} onChange={e=>{setTargetType(e.target.value);setPage(0)}} className="rounded-full bg-surface-container px-4 py-3"><option value="">All target types</option>{['REPORT','POST','COMMENT','USER'].map(x=><option key={x}>{x}</option>)}</select><input value={targetId} onChange={e=>{setTargetId(e.target.value);setPage(0)}} placeholder="Filter by target ID" className="rounded-full bg-surface-container px-4 py-3 outline-none focus:ring-2 focus:ring-primary"/></section>{query.isError&&<div role="alert" className="rounded-2xl bg-error-container p-4">Audit history could not be loaded.</div>}<section className="overflow-hidden rounded-3xl bg-surface-container-lowest">{query.isLoading?<div className="grid min-h-72 place-items-center">Loading audit history…</div>:!query.data?.content.length?<div className="grid min-h-72 place-items-center text-on-surface-variant"><ClipboardList className="mb-2"/>No matching actions.</div>:<div className="divide-y divide-outline-variant/20">{query.data.content.map(item=><article key={item.id} className="grid gap-2 p-5 sm:grid-cols-[220px_1fr_180px]"><div><b>{item.actionType.replaceAll('_',' ')}</b><p className="text-xs text-on-surface-variant">{item.targetType}</p></div><div><p className="text-sm">{item.reason}</p><p className="truncate text-xs text-on-surface-variant">Target: {item.targetId}</p>{item.note&&<p className="mt-1 text-sm text-on-surface-variant">{item.note}</p>}</div><time className="text-sm text-on-surface-variant">{new Date(item.createdAt).toLocaleString()}</time></article>)}</div>}<footer className="flex justify-end gap-3 border-t border-outline-variant/20 p-4"><button disabled={page===0} onClick={()=>setPage(p=>p-1)} className="p-2 disabled:opacity-30"><ChevronLeft/></button><span className="py-2 text-sm">Page {page+1}</span><button disabled={page+1>=(query.data?.totalPages??1)} onClick={()=>setPage(p=>p+1)} className="p-2 disabled:opacity-30"><ChevronRight/></button></footer></section></div></main>;
}
