import { Activity, Database, RefreshCw, Server } from 'lucide-react';
import { useAdminMonitoring } from './hooks/useAdminMonitoring';
import type { HealthStatus } from './types/admin.types';

const colors: Record<HealthStatus,string>={UP:'bg-green-100 text-green-700',DOWN:'bg-error-container text-on-error-container',UNKNOWN:'bg-surface-container-high text-on-surface-variant'};

export default function Monitoring(){
 const query=useAdminMonitoring(); const data=query.data; const total=data?.services.reduce((sum,item)=>sum+item.registeredInstances,0)??0;
 return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Operations</p><h2 className="mt-2 text-4xl font-semibold">System Monitoring</h2><p className="mt-2 text-on-surface-variant">Live service discovery and infrastructure connectivity.</p></div><button onClick={()=>void query.refetch()} disabled={query.isFetching} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 font-bold text-white disabled:opacity-60"><RefreshCw size={18} className={query.isFetching?'animate-spin':''}/>Refresh</button></header>
 {query.isError&&<div role="alert" className="rounded-2xl bg-error-container p-4 text-on-error-container">Monitoring data could not be loaded. Please try again.</div>}
 {data?.partialData&&<div role="status" className="rounded-2xl bg-secondary-container p-4">Some components are unavailable. Healthy components remain visible.</div>}
 {query.isLoading?<div className="grid min-h-80 place-items-center">Checking platform health…</div>:data&&<><section><div className="mb-4 flex items-center justify-between"><h3 className="text-xl font-semibold">Services</h3><span className="rounded-full bg-surface-container px-4 py-2 text-sm font-bold">{total} registered instances</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.services.map(service=><article key={service.serviceName} className="rounded-3xl border border-outline-variant/30 bg-surface-container-lowest p-5"><div className="flex items-start justify-between"><div className="rounded-2xl bg-primary-container/30 p-3 text-primary"><Server/></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${colors[service.status]}`}>{service.status}</span></div><h4 className="mt-5 text-xl font-semibold">{service.serviceName.replace('-service','')}</h4><p className="mt-1 text-sm text-on-surface-variant">{service.registeredInstances} instance{service.registeredInstances===1?'':'s'}</p><div className="mt-4 space-y-2">{service.instances.map(instance=><div key={instance.instanceId} className="rounded-xl bg-surface-container p-3 text-sm"><div className="flex justify-between"><b>{instance.host}:{instance.port}</b><span className={instance.status==='UP'?'text-green-700':instance.status==='DOWN'?'text-error':'text-on-surface-variant'}>{instance.status}</span></div><p className="mt-1 text-xs text-on-surface-variant">{instance.latencyMs} ms · {new Date(instance.checkedAt).toLocaleTimeString()}</p></div>)}</div></article>)}</div></section>
 <section><h3 className="mb-4 text-xl font-semibold">Infrastructure</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.infrastructure.map(item=><article key={item.component} className="rounded-3xl border border-outline-variant/30 bg-surface-container-lowest p-5"><div className="flex justify-between"><div className="rounded-2xl bg-surface-container p-3">{item.component.includes('SQL')||item.component.includes('Mongo')?<Database/>:<Activity/>}</div><span className={`rounded-full px-3 py-1 text-xs font-bold ${colors[item.status]}`}>{item.status}</span></div><h4 className="mt-5 text-lg font-semibold">{item.component}</h4><p className="mt-2 text-xs text-on-surface-variant">Sources: {item.sources.join(', ')}</p></article>)}</div></section><p className="text-right text-xs text-on-surface-variant">Last checked {new Date(data.checkedAt).toLocaleString()} · refreshes every 30 seconds while visible</p></>}
 </div></main>;
}
