import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Flag, RefreshCw, X } from 'lucide-react';
import { useAdminReports } from './hooks/useAdminReports';
import { useEscapeKey } from './hooks/useEscapeKey';

const reasons = ['SPAM','HARASSMENT','HATE_SPEECH','VIOLENCE','NUDITY','FALSE_INFORMATION','IMPERSONATION','OTHER'];
const actions = ['HIDE_CONTENT','REMOVE_CONTENT','SEND_WARNING','SUSPEND_USER','BAN_USER'];

export default function Reports() {
  const [status,setStatus]=useState('PENDING'); const [targetType,setTargetType]=useState(''); const [reasonFilter,setReasonFilter]=useState(''); const [page,setPage]=useState(0); const [selectedId,setSelectedId]=useState<string>();
  const [mode,setMode]=useState<'review'|'dismiss'|'resolve'>(); const [reason,setReason]=useState('HARASSMENT'); const [action,setAction]=useState('REMOVE_CONTENT'); const [note,setNote]=useState(''); const [until,setUntil]=useState('');
  const params=useMemo(()=>({status:status||undefined,targetType:targetType||undefined,reason:reasonFilter||undefined,page,size:20}),[status,targetType,reasonFilter,page]);
  const admin=useAdminReports(params,selectedId); const selected=admin.detail.data; const mutation=mode==='review'?admin.review:mode==='dismiss'?admin.dismiss:admin.resolve;
  const closeAction=()=>{setMode(undefined);setNote('');setUntil('')};
  const closeDetails=()=>{setSelectedId(undefined);setMode(undefined)};
  useEscapeKey(Boolean(mode), closeAction);
  useEscapeKey(Boolean(selectedId) && !mode, closeDetails);
  const submit=async()=>{if(!selectedId||!mode)return;if(mode==='review')await admin.review.mutateAsync({id:selectedId,adminNote:note||undefined});else if(mode==='dismiss')await admin.dismiss.mutateAsync({id:selectedId,moderationReason:reason,adminNote:note||undefined});else await admin.resolve.mutateAsync({id:selectedId,action,moderationReason:reason,adminNote:note||undefined,suspendedUntil:action==='SUSPEND_USER'&&until?new Date(until).toISOString():undefined});closeAction();await admin.detail.refetch();};
  return <main className="p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-primary">Trust & Safety</p><h2 className="mt-2 text-4xl font-semibold">Report Queue</h2><p className="mt-2 text-on-surface-variant">Review community reports and apply audited outcomes.</p></div><button onClick={()=>void admin.reports.refetch()} className="rounded-full bg-primary p-3 text-white"><RefreshCw size={20}/></button></header>
  <section className="grid gap-3 rounded-3xl bg-surface-container-lowest p-5 sm:grid-cols-3"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}} className="rounded-full bg-surface-container px-4 py-3"><option value="">All statuses</option>{['PENDING','REVIEWING','RESOLVED','DISMISSED'].map(x=><option key={x}>{x}</option>)}</select><select value={targetType} onChange={e=>{setTargetType(e.target.value);setPage(0)}} className="rounded-full bg-surface-container px-4 py-3"><option value="">All targets</option>{['POST','COMMENT','USER'].map(x=><option key={x}>{x}</option>)}</select><select value={reasonFilter} onChange={e=>{setReasonFilter(e.target.value);setPage(0)}} className="rounded-full bg-surface-container px-4 py-3"><option value="">All reasons</option>{reasons.map(x=><option key={x}>{x}</option>)}</select></section>
  {admin.reports.isError&&<div role="alert" className="rounded-2xl bg-error-container p-4 text-on-error-container">Reports could not be loaded. Please retry.</div>}
  <section className="overflow-hidden rounded-3xl bg-surface-container-lowest">{admin.reports.isLoading?<div className="grid min-h-72 place-items-center">Loading reports…</div>:!admin.reports.data?.content.length?<div className="grid min-h-72 place-items-center text-on-surface-variant">The queue is empty.</div>:<div className="divide-y divide-outline-variant/20">{admin.reports.data.content.map(report=><button key={report.id} onClick={()=>setSelectedId(report.id)} className="grid w-full gap-3 p-5 text-left hover:bg-surface-container sm:grid-cols-[1fr_160px_160px]"><div><span className="inline-flex items-center gap-2 font-bold text-primary"><Flag size={16}/>{report.targetType} · {report.reason}</span><p className="mt-1 line-clamp-2 text-sm text-on-surface-variant">{report.description||`Target ${report.targetId}`}</p></div><span className="text-sm font-bold">{report.status}</span><span className="text-sm text-on-surface-variant">{new Date(report.createdAt).toLocaleString()}</span></button>)}</div>}<footer className="flex items-center justify-between border-t border-outline-variant/20 p-4"><span className="text-sm text-on-surface-variant">{admin.reports.data?.totalElements??0} reports</span><div className="flex items-center"><button disabled={page===0} onClick={()=>setPage(p=>p-1)} className="p-2 disabled:opacity-30"><ChevronLeft/></button><span className="px-3 text-sm">{page+1}</span><button disabled={page+1>=(admin.reports.data?.totalPages??1)} onClick={()=>setPage(p=>p+1)} className="p-2 disabled:opacity-30"><ChevronRight/></button></div></footer></section></div>
  {selectedId&&<div className="fixed inset-0 z-40 flex justify-end bg-black/30" onClick={()=>setSelectedId(undefined)}><aside onClick={e=>e.stopPropagation()} className="h-full w-full max-w-2xl overflow-y-auto bg-surface p-6 shadow-xl"><button onClick={()=>setSelectedId(undefined)} className="float-right p-2"><X/></button>{admin.detail.isLoading?<p>Loading report…</p>:admin.detail.isError?<p role="alert" className="rounded-xl bg-error-container p-4">Report detail could not be loaded.</p>:selected&&<><p className="text-xs font-bold uppercase tracking-widest text-primary">{selected.report.status}</p><h3 className="mt-2 text-3xl font-semibold">{selected.report.targetType} report</h3><p className="mt-2 text-on-surface-variant">{selected.report.reason} · {selected.aggregateReportCount} reports on this target</p>{selected.partialData&&<p className="mt-4 rounded-xl bg-secondary-container p-3">Partial content data: {selected.unavailableComponents.join(', ')}</p>}<section className="mt-6 rounded-2xl bg-surface-container p-5"><h4 className="font-bold">Reported content</h4><p className="mt-3 whitespace-pre-wrap">{selected.targetContent?.content||'Content is unavailable or this report targets a user.'}</p>{selected.targetContent?.media?.map((media,i)=><a key={i} href={media.url} target="_blank" rel="noreferrer" className="mt-3 block text-primary underline">View {media.type.toLowerCase()}</a>)}</section><section className="mt-4 rounded-2xl bg-surface-container p-5"><h4 className="font-bold">Reporter description</h4><p className="mt-2">{selected.report.description||'No description provided.'}</p></section>{!['RESOLVED','DISMISSED'].includes(selected.report.status)&&<div className="mt-6 flex flex-wrap gap-2">{selected.report.status==='PENDING'&&<button onClick={()=>setMode('review')} className="rounded-full bg-secondary px-5 py-3 font-bold text-white">Start review</button>}<button onClick={()=>setMode('dismiss')} className="rounded-full bg-surface-container px-5 py-3 font-bold">Dismiss</button><button onClick={()=>setMode('resolve')} className="rounded-full bg-primary px-5 py-3 font-bold text-white">Resolve</button></div>}</>}</aside></div>}
  {selectedId&&mode&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><form onSubmit={e=>{e.preventDefault();void submit()}} className="w-full max-w-lg rounded-3xl bg-surface p-6"><button type="button" onClick={closeAction} className="float-right"><X/></button><h3 className="text-2xl font-semibold capitalize">{mode} report</h3>{mutation.error&&<p role="alert" className="mt-4 rounded-xl bg-error-container p-3">The moderation action failed. Refresh the report and try again.</p>}{mode==='resolve'&&<label className="mt-5 block text-sm font-bold">Action<select value={action} onChange={e=>setAction(e.target.value)} className="mt-2 w-full rounded-2xl bg-surface-container p-3">{actions.map(x=><option key={x}>{x}</option>)}</select></label>}{mode!=='review'&&<label className="mt-4 block text-sm font-bold">Reason<select value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 w-full rounded-2xl bg-surface-container p-3">{reasons.map(x=><option key={x}>{x}</option>)}</select></label>}{mode==='resolve'&&action==='SUSPEND_USER'&&<label className="mt-4 block text-sm font-bold">Suspended until<input required type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)} className="mt-2 w-full rounded-2xl bg-surface-container p-3"/></label>}<label className="mt-4 block text-sm font-bold">Private admin note<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-2 w-full rounded-2xl bg-surface-container p-3"/></label><button disabled={mutation.isPending} className="mt-6 w-full rounded-full bg-primary py-3 font-bold text-white disabled:opacity-50">{mutation.isPending?'Applying…':'Confirm'}</button></form></div>}
  </main>;
}
